export const cardsAcceptedCodeMap = {
  all: 'All',
  A: 'American Express',
  CREDIT: 'Credit',
  Debit: 'Debit',
  D: 'Discover',
  M: 'MasterCard',
  V: 'Visa',
  Cash: 'Cash',
  Checks: 'Check',
  ACCOUNT_BALANCE: 'Account Balance',
  ALLIANCE: 'Alliance AutoGas',
  ANDROID_PAY: 'Android Pay',
  APPLE_PAY: 'Apple Pay',
  ARI: 'ARI',
  CleanEnergy: 'Clean Energy',
  Comdata: 'Comdata',
  CFN: 'Commercial Fueling Network',
  EFS: 'EFS',
  FleetOne: 'Fleet One',
  FuelMan: 'Fuelman',
  GasCard: 'GASCARD',
  PacificPride: 'Pacific Pride',
  PHH: 'PHH',
  Proprietor: 'Proprietor Fleet Card',
  Speedway: 'Speedway',
  SuperPass: 'SuperPass',
  TCH: 'TCH',
  Tchek: 'T-Chek T-Card',
  Trillium: 'Trillium',
  Voyager: 'Voyager',
  Wright_Exp: 'WEX',
};

export const accessDetailCodeMap = {
  CALL: 'Call ahead',
  KEY_AFTER_HOURS: 'Card key after hours',
  KEY_ALWAYS: 'Card key at all times',
  CREDIT_CARD_AFTER_HOURS: 'Credit card after hours',
  CREDIT_CARD_ALWAYS: 'Credit card at all times',
  FLEET: 'Fleet customers only',
  GOVERNMENT: 'Government only',
  LIMITED_HOURS: 'Limited hours',
  RESIDENTIAL: 'Residential',
};

export const facilityTypesMap = {
  AIRPORT: 'Airport',
  ARENA: 'Arena',
  AUTO_REPAIR: 'Auto Repair Shop',
  BANK: 'Bank',
  B_AND_B: 'B&B',
  BREWERY_DISTILLERY_WINERY: 'Brewery/Distillery/Winery',
  CAMPGROUND: 'Campground',
  CAR_DEALER: 'Car Dealer',
  CARWASH: 'Carwash',
  COLLEGE_CAMPUS: 'College Campus',
  CONVENIENCE_STORE: 'Convenience Store',
  CONVENTION_CENTER: 'Convention Center',
  COOP: 'Co-Op',
  FACTORY: 'Factory',
  FED_GOV: 'Federal Government',
  FIRE_STATION: 'Fire Station',
  FLEET_GARAGE: 'Fleet Garage',
  FUEL_RESELLER: 'Fuel Reseller',
  GROCERY: 'Grocery Store',
  HARDWARE_STORE: 'Hardware Store',
  HOSPITAL: 'Hospital',
  HOTEL: 'Hotel',
  INN: 'Inn',
  LIBRARY: 'Library',
  MIL_BASE: 'Military Base',
  MOTOR_POOL: 'Motor Pool',
  MULTI_UNIT_DWELLING: 'Multi-Family Housing',
  MUNI_GOV: 'Municipal Government',
  MUSEUM: 'Museum',
  NATL_PARK: 'National Park',
  OFFICE_BLDG: 'Office Building',
  OTHER: 'Other',
  OTHER_ENTERTAINMENT: 'Other Entertainment',
  PARK: 'Park',
  PARKING_GARAGE: 'Parking Garage',
  PARKING_LOT: 'Parking Lot',
  PAY_GARAGE: 'Pay-Parking Garage',
  PAY_LOT: 'Pay-Parking Lot',
  PHARMACY: 'Pharmacy',
  PLACE_OF_WORSHIP: 'Place of Worship',
  PRISON: 'Prison',
  PUBLIC: 'Public',
  REC_SPORTS_FACILITY: 'Recreational Sports Facility',
  REFINERY: 'Refinery',
  RENTAL_CAR_RETURN: 'Rental Car Return',
  RESEARCH_FACILITY: 'Research Facility/Laboratory',
  RESTAURANT: 'Restaurant',
  REST_STOP: 'Rest Stop',
  RETAIL: 'Retail',
  RV_PARK: 'RV Park',
  SCHOOL: 'School',
  GAS_STATION: 'Service/Gas Station',
  SHOPPING_CENTER: 'Shopping Center',
  SHOPPING_MALL: 'Shopping Mall',
  STADIUM: 'Stadium',
  STANDALONE_STATION: 'Standalone Station',
  STATE_GOV: 'State/Provincial Government',
  STORAGE: 'Storage Facility',
  STREET_PARKING: 'Street Parking',
  TNC: 'Transportation Network Company',
  TRAVEL_CENTER: 'Travel Center',
  TRUCK_STOP: 'Truck Stop',
  UTILITY: 'Utility',
  WORKPLACE: 'Workplace',
};

// TODO: this could be pulled out via react ctx or lib like zustand
export interface RouteDurationOverview {
  totalSeconds: number;
  totalMeters: number;
}
